### PR TITLE
Adding a `float` keyword

### PR DESCRIPTION
**Pull request by oleks**
Shortly resurfaces #118.

### CODE REVIEW

**Comment by oleks** [comment]
Speaking of.. Why is f64 the default when this is bad for GPU performance?

**Comment by Athas** [comment]
Oleks <notifications@github.com> writes:

> Speaking of.. Why is f64 the default when this is bad for GPU performance?

It is the default in C.

-- 
\  Troels
/\ Henriksen

**Comment by oleks** [comment]
On Fri, Mar 4, 2016 at 1:32 AM, Troels Henriksen
<notifications@github.com> wrote:
> Oleks <notifications@github.com> writes:
>
> > Speaking of.. Why is f64 the default when this is bad for GPU performance?
>
> It is the default in C.

Right.

**Comment by Athas** [comment]
What is the point of this?

**Comment by oleks** [comment]
On Fri, Mar 4, 2016 at 8:29 AM, Troels Henriksen <notifications@github.com>
wrote:

> What is the point of this?
>

It's just like there's an int keyword.

For instance, if I want to go ahead and *chage* the default float-type it
is as easy as changing the default declaration at the top of my file.

**Pull request merged**
