### PR TITLE
Purge real keyword

### PR DESCRIPTION
**Pull request by oleks**
So this finally happened.

@Athas

### CODE REVIEW

**Comment by Athas** [comment]
Should I resolve the conflicts?

**Comment by oleks** [comment]
> Should I resolve the conflicts?

Yes, I don't have time for that, gotta go fast ;-)

But do you have a nice way of seeing where the conflicts are?

**Comment by Athas** [comment]
Oleks <notifications@github.com> writes:

>> Should I resolve the conflicts?
>
> Yes, I don't have time for that, gotta go fast ;-)
>
> But do you have a nice way of seeing where the conflicts are?

I do a merge and then Git tells me.

-- 
\  Troels
/\ Henriksen

**Comment by oleks** [comment]
On Mon, Feb 29, 2016 at 8:22 AM, Troels Henriksen
<notifications@github.com> wrote:
>
> Oleks <notifications@github.com> writes:
>
> >> Should I resolve the conflicts?
> >
> > Yes, I don't have time for that, gotta go fast ;-)
> >
> > But do you have a nice way of seeing where the conflicts are?
>
> I do a merge and then Git tells me.

In the real world, people fix conflicts before making pull requests..
so working on it :-)

**Pull request merged**
